// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: aGwaDyFceaTJ7MmVgLqAKM
// Component: v-yXxSNs9o0
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: 72kuX7z4jE2/component
import { SupabaseQuery } from "../../CodeComponents/DatabaseComponents"; // plasmic-import: xgGmBGYFNNC/codeComponent
import { SupabaseGridCollection } from "../../CodeComponents/DisplayCollections"; // plasmic-import: oT7etggpiceX/codeComponent
import Post from "../../Post"; // plasmic-import: dZQFlEuvgPR/component
import { SupabaseTextField } from "../../CodeComponents/DisplayCollections"; // plasmic-import: lFC9CRSs6Y-w/codeComponent
import { SupabaseImgField } from "../../CodeComponents/DisplayCollections"; // plasmic-import: m-q4KZlXkHnO/codeComponent

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_copy_of_supabase.module.css"; // plasmic-import: aGwaDyFceaTJ7MmVgLqAKM/projectcss
import sty from "./PlasmicPosts.module.css"; // plasmic-import: v-yXxSNs9o0/css

import PlusIcon from "./icons/PlasmicIcon__Plus"; // plasmic-import: 6s1jELwioiIP/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: -NPp1PMkI3Mu/icon

export type PlasmicPosts__VariantMembers = {};

export type PlasmicPosts__VariantsArgs = {};
type VariantPropType = keyof PlasmicPosts__VariantsArgs;
export const PlasmicPosts__VariantProps = new Array<VariantPropType>();

export type PlasmicPosts__ArgsType = {};
type ArgPropType = keyof PlasmicPosts__ArgsType;
export const PlasmicPosts__ArgProps = new Array<ArgPropType>();

export type PlasmicPosts__OverridesType = {
  root?: p.Flex<"div">;
  h2?: p.Flex<"h2">;
  freeBox?: p.Flex<"div">;
  button?: p.Flex<typeof Button>;
  svg?: p.Flex<"svg">;
  supabaseQuery?: p.Flex<typeof SupabaseQuery>;
  supabaseGridCollection?: p.Flex<typeof SupabaseGridCollection>;
  post?: p.Flex<typeof Post>;
  supabaseImgField?: p.Flex<typeof SupabaseImgField>;
  img?: p.Flex<typeof p.PlasmicImg>;
};

export interface DefaultPostsProps {
  className?: string;
}

function PlasmicPosts__RenderFunc(props: {
  variants: PlasmicPosts__VariantsArgs;
  args: PlasmicPosts__ArgsType;
  overrides: PlasmicPosts__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text___05Uc
        )}
      >
        <React.Fragment>
          <React.Fragment>{""}</React.Fragment>
          <h2
            data-plasmic-name={"h2"}
            data-plasmic-override={overrides.h2}
            className={classNames(
              projectcss.all,
              projectcss.h2,
              projectcss.__wab_text,
              sty.h2
            )}
          >
            {"Posts"}
          </h2>
          <React.Fragment>{""}</React.Fragment>
        </React.Fragment>
      </div>

      {true ? (
        <div
          data-plasmic-name={"freeBox"}
          data-plasmic-override={overrides.freeBox}
          className={classNames(projectcss.all, sty.freeBox)}
        >
          <Button
            data-plasmic-name={"button"}
            data-plasmic-override={overrides.button}
            className={classNames("__wab_instance", sty.button)}
            color={"softSand" as const}
            link={"/post/add" as const}
            showStartIcon={true}
            size={"compact" as const}
            startIcon={
              <PlusIcon
                data-plasmic-name={"svg"}
                data-plasmic-override={overrides.svg}
                className={classNames(projectcss.all, sty.svg)}
                role={"img"}
              />
            }
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__rUE
              )}
            >
              {"New Post"}
            </div>
          </Button>
        </div>
      ) : null}

      <SupabaseQuery
        data-plasmic-name={"supabaseQuery"}
        data-plasmic-override={overrides.supabaseQuery}
        className={classNames("__wab_instance", sty.supabaseQuery)}
        columns={"title, content, id, imageUrl" as const}
        tableName={"posts" as const}
      >
        <SupabaseGridCollection
          data-plasmic-name={"supabaseGridCollection"}
          data-plasmic-override={overrides.supabaseGridCollection}
          className={classNames("__wab_instance", sty.supabaseGridCollection)}
          columnGap={50 as const}
          columns={3 as const}
          loading={
            <p.PlasmicImg
              data-plasmic-name={"img"}
              data-plasmic-override={overrides.img}
              alt={""}
              className={classNames(sty.img)}
              displayHeight={"auto" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: "/plasmic/copy_of_supabase/images/loadingIconjpeg.gif",
                fullWidth: 800,
                fullHeight: 600,
                aspectRatio: undefined
              }}
            />
          }
          rowGap={30 as const}
          testLoading={false}
        >
          <Post
            data-plasmic-name={"post"}
            data-plasmic-override={overrides.post}
            className={classNames("__wab_instance", sty.post)}
            description={
              <SupabaseTextField
                className={classNames(
                  "__wab_instance",
                  sty.supabaseTextField___7UHvf
                )}
                name={"{{row.content}}" as const}
              />
            }
            image={
              <SupabaseImgField
                data-plasmic-name={"supabaseImgField"}
                data-plasmic-override={overrides.supabaseImgField}
                className={classNames("__wab_instance", sty.supabaseImgField)}
                url={"{{row.imageUrl}}" as const}
              />
            }
            title={
              <SupabaseTextField
                className={classNames(
                  "__wab_instance",
                  sty.supabaseTextField__uSg9R
                )}
                name={"{{row.title}}" as const}
              />
            }
          />
        </SupabaseGridCollection>
      </SupabaseQuery>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "h2",
    "freeBox",
    "button",
    "svg",
    "supabaseQuery",
    "supabaseGridCollection",
    "post",
    "supabaseImgField",
    "img"
  ],
  h2: ["h2"],
  freeBox: ["freeBox", "button", "svg"],
  button: ["button", "svg"],
  svg: ["svg"],
  supabaseQuery: [
    "supabaseQuery",
    "supabaseGridCollection",
    "post",
    "supabaseImgField",
    "img"
  ],
  supabaseGridCollection: [
    "supabaseGridCollection",
    "post",
    "supabaseImgField",
    "img"
  ],
  post: ["post", "supabaseImgField"],
  supabaseImgField: ["supabaseImgField"],
  img: ["img"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  h2: "h2";
  freeBox: "div";
  button: typeof Button;
  svg: "svg";
  supabaseQuery: typeof SupabaseQuery;
  supabaseGridCollection: typeof SupabaseGridCollection;
  post: typeof Post;
  supabaseImgField: typeof SupabaseImgField;
  img: typeof p.PlasmicImg;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPosts__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPosts__VariantsArgs;
    args?: PlasmicPosts__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPosts__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPosts__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPosts__ArgProps,
      internalVariantPropNames: PlasmicPosts__VariantProps
    });

    return PlasmicPosts__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPosts";
  } else {
    func.displayName = `PlasmicPosts.${nodeName}`;
  }
  return func;
}

export const PlasmicPosts = Object.assign(
  // Top-level PlasmicPosts renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h2: makeNodeComponent("h2"),
    freeBox: makeNodeComponent("freeBox"),
    button: makeNodeComponent("button"),
    svg: makeNodeComponent("svg"),
    supabaseQuery: makeNodeComponent("supabaseQuery"),
    supabaseGridCollection: makeNodeComponent("supabaseGridCollection"),
    post: makeNodeComponent("post"),
    supabaseImgField: makeNodeComponent("supabaseImgField"),
    img: makeNodeComponent("img"),

    // Metadata about props expected for PlasmicPosts
    internalVariantProps: PlasmicPosts__VariantProps,
    internalArgProps: PlasmicPosts__ArgProps
  }
);

export default PlasmicPosts;
/* prettier-ignore-end */
