// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: aGwaDyFceaTJ7MmVgLqAKM
// Component: VKWOfitnL5VD
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { SupabaseQuery } from "../../CodeComponents/DatabaseComponents"; // plasmic-import: xgGmBGYFNNC/codeComponent
import { SupabaseGridCollection } from "../../CodeComponents/DisplayCollections"; // plasmic-import: oT7etggpiceX/codeComponent
import { SupabaseTextField } from "../../CodeComponents/DisplayCollections"; // plasmic-import: lFC9CRSs6Y-w/codeComponent
import { SupabaseImgField } from "../../CodeComponents/DisplayCollections"; // plasmic-import: m-q4KZlXkHnO/codeComponent
import { SupabaseEditButton } from "../../CodeComponents/UtilsComponents"; // plasmic-import: WwsEYXP7mwRu/codeComponent
import { SupabaseDeleteButton } from "../../CodeComponents/UtilsComponents"; // plasmic-import: qhy5MYQZKe_S/codeComponent
import { SupabaseMutation } from "../../CodeComponents/DatabaseComponents"; // plasmic-import: 4TsbaDRppPhb/codeComponent
import { SupabaseModal } from "../../CodeComponents/UtilsComponents"; // plasmic-import: 1xO-DTXyIZ-x/codeComponent
import { SupabaseTableCollection } from "../../CodeComponents/DisplayCollections"; // plasmic-import: AZq778uV6Dli/codeComponent

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_copy_of_supabase.module.css"; // plasmic-import: aGwaDyFceaTJ7MmVgLqAKM/projectcss
import sty from "./PlasmicMountain.module.css"; // plasmic-import: VKWOfitnL5VD/css

import EditIcon from "./icons/PlasmicIcon__Edit"; // plasmic-import: z0nK1hBoU9-T/icon
import DeleteIcon from "./icons/PlasmicIcon__Delete"; // plasmic-import: RfsqmqGRFWpt/icon

export type PlasmicMountain__VariantMembers = {};

export type PlasmicMountain__VariantsArgs = {};
type VariantPropType = keyof PlasmicMountain__VariantsArgs;
export const PlasmicMountain__VariantProps = new Array<VariantPropType>();

export type PlasmicMountain__ArgsType = {};
type ArgPropType = keyof PlasmicMountain__ArgsType;
export const PlasmicMountain__ArgProps = new Array<ArgPropType>();

export type PlasmicMountain__OverridesType = {
  root?: p.Flex<"div">;
  supabaseQuery?: p.Flex<typeof SupabaseQuery>;
  supabaseGridCollection?: p.Flex<typeof SupabaseGridCollection>;
  freeBox?: p.Flex<"div">;
  supabaseImgField?: p.Flex<typeof SupabaseImgField>;
  supabaseEditButton?: p.Flex<typeof SupabaseEditButton>;
  supabaseTableCollection?: p.Flex<typeof SupabaseTableCollection>;
};

export interface DefaultMountainProps {}

function PlasmicMountain__RenderFunc(props: {
  variants: PlasmicMountain__VariantsArgs;
  args: PlasmicMountain__ArgsType;
  overrides: PlasmicMountain__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <SupabaseQuery
            data-plasmic-name={"supabaseQuery"}
            data-plasmic-override={overrides.supabaseQuery}
            className={classNames("__wab_instance", sty.supabaseQuery)}
            columns={"mountain, location, imageUrl" as const}
            tableName={"mountains" as const}
          >
            <SupabaseGridCollection
              data-plasmic-name={"supabaseGridCollection"}
              data-plasmic-override={overrides.supabaseGridCollection}
              className={classNames(
                "__wab_instance",
                sty.supabaseGridCollection
              )}
              columnGap={16 as const}
              columns={2 as const}
              count={undefined}
              loading={
                <React.Fragment>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__aM2Cz)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/copy_of_supabase/images/loading2.gif",
                      fullWidth: 200,
                      fullHeight: 200,
                      aspectRatio: undefined
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__l560Z)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: "/plasmic/copy_of_supabase/images/loading.gif",
                      fullWidth: 300,
                      fullHeight: 300,
                      aspectRatio: undefined
                    }}
                  />
                </React.Fragment>
              }
              rowGap={16 as const}
              testLoading={false}
            >
              <div
                data-plasmic-name={"freeBox"}
                data-plasmic-override={overrides.freeBox}
                className={classNames(projectcss.all, sty.freeBox)}
              >
                <SupabaseTextField
                  className={classNames(
                    "__wab_instance",
                    sty.supabaseTextField__s3XRm
                  )}
                  name={"{{row.mountain}}" as const}
                />

                <SupabaseTextField
                  className={classNames(
                    "__wab_instance",
                    sty.supabaseTextField__ll8Aw
                  )}
                  name={"{{row.location}}" as const}
                />

                <SupabaseImgField
                  data-plasmic-name={"supabaseImgField"}
                  data-plasmic-override={overrides.supabaseImgField}
                  className={classNames("__wab_instance", sty.supabaseImgField)}
                  url={"{{row.imageUrl}}" as const}
                />

                <SupabaseEditButton
                  data-plasmic-name={"supabaseEditButton"}
                  data-plasmic-override={overrides.supabaseEditButton}
                  className={classNames(
                    "__wab_instance",
                    sty.supabaseEditButton
                  )}
                  editPage={"/mountain/edit" as const}
                  id={"{{row.id}}" as const}
                >
                  <EditIcon
                    className={classNames(projectcss.all, sty.svg__hxsC8)}
                    role={"img"}
                  />
                </SupabaseEditButton>

                <SupabaseDeleteButton
                  className={classNames(
                    "__wab_instance",
                    sty.supabaseDeleteButton__quRk6
                  )}
                  id={"{{row.id}}" as const}
                  modal={
                    <SupabaseMutation
                      className={classNames(
                        "__wab_instance",
                        sty.supabaseMutation__wZqhK
                      )}
                      filters={[
                        {
                          name: "eq",
                          args: [{ column: "id", value: "{{row.id}}" }]
                        }
                      ]}
                      method={"delete" as const}
                      redirectOnSuccess={"/mountain" as const}
                      tableName={"mountains" as const}
                    >
                      <SupabaseModal
                        className={classNames(
                          "__wab_instance",
                          sty.supabaseModal__yLLnz
                        )}
                        showModal={false}
                      >
                        <SupabaseTextField
                          className={classNames(
                            "__wab_instance",
                            sty.supabaseTextField__vm3Ey
                          )}
                          name={"{{row.mountain}}" as const}
                        />
                      </SupabaseModal>
                    </SupabaseMutation>
                  }
                >
                  <DeleteIcon
                    className={classNames(projectcss.all, sty.svg__nUjrx)}
                    role={"img"}
                  />
                </SupabaseDeleteButton>
              </div>
            </SupabaseGridCollection>

            <SupabaseTableCollection
              data-plasmic-name={"supabaseTableCollection"}
              data-plasmic-override={overrides.supabaseTableCollection}
              canDelete={true}
              canEdit={true}
              className={classNames(
                "__wab_instance",
                sty.supabaseTableCollection
              )}
              columns={"mountain,location,imageUrl" as const}
              deleteSlot={
                <SupabaseDeleteButton
                  className={classNames(
                    "__wab_instance",
                    sty.supabaseDeleteButton__a3Ev
                  )}
                  id={"{{row.id}}" as const}
                  modal={
                    <SupabaseMutation
                      className={classNames(
                        "__wab_instance",
                        sty.supabaseMutation___5YqOn
                      )}
                      filters={[
                        {
                          name: "eq",
                          args: [{ column: "id", value: "{{row.id}}" }]
                        }
                      ]}
                      method={"delete" as const}
                      redirectOnSuccess={"/mountain" as const}
                      tableName={"mountains" as const}
                    >
                      <SupabaseModal
                        className={classNames(
                          "__wab_instance",
                          sty.supabaseModal__hvWjg
                        )}
                        showModal={false}
                      >
                        <SupabaseTextField
                          className={classNames(
                            "__wab_instance",
                            sty.supabaseTextField__o0G9L
                          )}
                          name={"{{row.mountain}}" as const}
                        />
                      </SupabaseModal>
                    </SupabaseMutation>
                  }
                >
                  <DeleteIcon
                    className={classNames(projectcss.all, sty.svg__e6MMk)}
                    role={"img"}
                  />
                </SupabaseDeleteButton>
              }
              editSlot={
                <EditIcon
                  className={classNames(projectcss.all, sty.svg__gArBx)}
                  role={"img"}
                />
              }
              loading={"Loading..."}
            />
          </SupabaseQuery>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "supabaseQuery",
    "supabaseGridCollection",
    "freeBox",
    "supabaseImgField",
    "supabaseEditButton",
    "supabaseTableCollection"
  ],
  supabaseQuery: [
    "supabaseQuery",
    "supabaseGridCollection",
    "freeBox",
    "supabaseImgField",
    "supabaseEditButton",
    "supabaseTableCollection"
  ],
  supabaseGridCollection: [
    "supabaseGridCollection",
    "freeBox",
    "supabaseImgField",
    "supabaseEditButton"
  ],
  freeBox: ["freeBox", "supabaseImgField", "supabaseEditButton"],
  supabaseImgField: ["supabaseImgField"],
  supabaseEditButton: ["supabaseEditButton"],
  supabaseTableCollection: ["supabaseTableCollection"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  supabaseQuery: typeof SupabaseQuery;
  supabaseGridCollection: typeof SupabaseGridCollection;
  freeBox: "div";
  supabaseImgField: typeof SupabaseImgField;
  supabaseEditButton: typeof SupabaseEditButton;
  supabaseTableCollection: typeof SupabaseTableCollection;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMountain__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMountain__VariantsArgs;
    args?: PlasmicMountain__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicMountain__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMountain__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMountain__ArgProps,
      internalVariantPropNames: PlasmicMountain__VariantProps
    });

    return PlasmicMountain__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMountain";
  } else {
    func.displayName = `PlasmicMountain.${nodeName}`;
  }
  return func;
}

export const PlasmicMountain = Object.assign(
  // Top-level PlasmicMountain renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    supabaseQuery: makeNodeComponent("supabaseQuery"),
    supabaseGridCollection: makeNodeComponent("supabaseGridCollection"),
    freeBox: makeNodeComponent("freeBox"),
    supabaseImgField: makeNodeComponent("supabaseImgField"),
    supabaseEditButton: makeNodeComponent("supabaseEditButton"),
    supabaseTableCollection: makeNodeComponent("supabaseTableCollection"),

    // Metadata about props expected for PlasmicMountain
    internalVariantProps: PlasmicMountain__VariantProps,
    internalArgProps: PlasmicMountain__ArgProps
  }
);

export default PlasmicMountain;
/* prettier-ignore-end */
